## docker-compose.yml 
version: '3.8' 

services:
  db:
    build: 
      context: .
      dockerfile: Dockerfile.postgres 
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: appraisal_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 8006:5432
    networks:
      - test_network
    
  pgadmin4:
    build: 
      context: .
      dockerfile: dockerfile.pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "localhost@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "password"
    ports:
      - "8005:80"
    depends_on:
      - db
    networks:
      - test_network
    volumes:
      - ./pgadmin_data:/var/lib/pgadmin/data


  web:
    build: ./app 
    # command: uvicorn backend.app.main:app --host 0.0.0.0 
    environment:
      DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/appraisal_db"
    restart: always
    depends_on:
      - db
    volumes:
      - ./app:/app 
    ports:
      - 8000:8000
    networks: 
      - test_network 
     
      
networks: 
  test_network:
    driver: bridge

volumes:
  postgres-data:
    driver: local